name: 🚀 Feature Request
description: Suggestion & deas for new features and improvements!
title: "[FEATURE] "
labels: enhancement

body:
    - type: textarea
      id: description
      attributes:
          label: Description
          description: A clear and concise description of the new feature
      validations:
          required: true
    - type: textarea
      id: example
      attributes:
          label: Example
          description: |
              A simple example of the new feature in action (URL, screenshots, videos, etc)
              If the new feature changes an existing feature, you can include a simple before/after comparison.
